---

* name: Deploy Todo App to Kubernetes
  hosts: localhost
  connection: local

  tasks:

  * name: Deploy Application
    command: kubectl apply -f Kubernetes/deployment.yaml

  * name: Create Service
    command: kubectl apply -f Kubernetes/service.yaml

  * name: Verify Rollout
    command: kubectl rollout status deployment/todo-app
